// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPG.DAL;

namespace RPG.DAL.Migrations
{
    [DbContext(typeof(RpgContext))]
    [Migration("20210525070101_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RPG.Entities.Character.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CharacterTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("SexId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTypeId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SexId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RPG.Entities.Character.CharacterTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("CharacterTypes");
                });

            modelBuilder.Entity("RPG.Entities.Character.EquipmentSlotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EquipmentSlots");
                });

            modelBuilder.Entity("RPG.Entities.Character.SexEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Sexes");
                });

            modelBuilder.Entity("RPG.Entities.Character.WeaponSlotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeaponSlots");
                });

            modelBuilder.Entity("RPG.Entities.Equipment.CharacterEquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentSlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EquipmentSlotId");

                    b.ToTable("CharacterEquipment");
                });

            modelBuilder.Entity("RPG.Entities.Equipment.EquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("RPG.Entities.Equipment.EquipmentTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacterTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EquipmentSlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTypeId");

                    b.HasIndex("EquipmentSlotId");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("RPG.Entities.Player.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RPG.Entities.Weapon.CharacterWeaponEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponSlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("WeaponId");

                    b.HasIndex("WeaponSlotId");

                    b.ToTable("CharacterWeapons");
                });

            modelBuilder.Entity("RPG.Entities.Weapon.WeaponEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("WeaponTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("RPG.Entities.Weapon.WeaponTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacterTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WeaponSlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTypeId");

                    b.HasIndex("WeaponSlotId");

                    b.ToTable("WeaponTypes");
                });

            modelBuilder.Entity("RPG.Entities.Character.CharacterEntity", b =>
                {
                    b.HasOne("RPG.Entities.Character.CharacterTypeEntity", "CharacterType")
                        .WithMany()
                        .HasForeignKey("CharacterTypeId");

                    b.HasOne("RPG.Entities.Player.PlayerEntity", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG.Entities.Character.SexEntity", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId");

                    b.Navigation("CharacterType");

                    b.Navigation("Player");

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("RPG.Entities.Equipment.CharacterEquipmentEntity", b =>
                {
                    b.HasOne("RPG.Entities.Character.CharacterEntity", "Character")
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG.Entities.Equipment.EquipmentEntity", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG.Entities.Character.EquipmentSlotEntity", "EquipmentSlot")
                        .WithMany()
                        .HasForeignKey("EquipmentSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Equipment");

                    b.Navigation("EquipmentSlot");
                });

            modelBuilder.Entity("RPG.Entities.Equipment.EquipmentEntity", b =>
                {
                    b.HasOne("RPG.Entities.Equipment.EquipmentTypeEntity", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("RPG.Entities.Equipment.EquipmentTypeEntity", b =>
                {
                    b.HasOne("RPG.Entities.Character.CharacterTypeEntity", "CharacterType")
                        .WithMany()
                        .HasForeignKey("CharacterTypeId");

                    b.HasOne("RPG.Entities.Character.EquipmentSlotEntity", "EquipmentSlot")
                        .WithMany()
                        .HasForeignKey("EquipmentSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterType");

                    b.Navigation("EquipmentSlot");
                });

            modelBuilder.Entity("RPG.Entities.Weapon.CharacterWeaponEntity", b =>
                {
                    b.HasOne("RPG.Entities.Character.CharacterEntity", "Character")
                        .WithMany("Weapons")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG.Entities.Weapon.WeaponEntity", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPG.Entities.Character.WeaponSlotEntity", "WeaponSlot")
                        .WithMany()
                        .HasForeignKey("WeaponSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Weapon");

                    b.Navigation("WeaponSlot");
                });

            modelBuilder.Entity("RPG.Entities.Weapon.WeaponEntity", b =>
                {
                    b.HasOne("RPG.Entities.Weapon.WeaponTypeEntity", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("RPG.Entities.Weapon.WeaponTypeEntity", b =>
                {
                    b.HasOne("RPG.Entities.Character.CharacterTypeEntity", "CharacterType")
                        .WithMany()
                        .HasForeignKey("CharacterTypeId");

                    b.HasOne("RPG.Entities.Character.WeaponSlotEntity", "WeaponSlot")
                        .WithMany()
                        .HasForeignKey("WeaponSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterType");

                    b.Navigation("WeaponSlot");
                });

            modelBuilder.Entity("RPG.Entities.Character.CharacterEntity", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPG.Entities.Player.PlayerEntity", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
